In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import joblib
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [2]:
fraud_df = pd.read_csv("../data/onlinefraud.csv", header = 0, sep = ',')

In [3]:
fraud_df.head(5)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [4]:
fraud_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            str
 2   amount          float64
 3   nameOrig        str
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        str
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), str(3)
memory usage: 706.2 MB

In [5]:
fraud_df.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
mean,2.433972e+02,1.798619e+05,8.338831e+05,8.551137e+05,1.100702e+06,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,6.038582e+05,2.888243e+06,2.924049e+06,3.399180e+06,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,1.338957e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,7.487194e+04,1.420800e+04,0.000000e+00,1.327057e+05,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.087215e+05,1.073152e+05,1.442584e+05,9.430367e+05,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,9.244552e+07,5.958504e+07,4.958504e+07,3.560159e+08,3.561793e+08,1.000000e+00,1.000000e+00

In [6]:
fraud_df['isFlaggedFraud'].value_counts()

isFlaggedFraud
0    6362604
1         16
Name: count, dtype: int64

In [7]:
fraud_df['isFraud'].value_counts()

isFraud
0    6354407
1       8213
Name: count, dtype: int64

In [8]:
fraud_df.drop(columns=['isFlaggedFraud'], inplace=True)

In [9]:
fraud_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 10 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            str
 2   amount          float64
 3   nameOrig        str
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        str
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
dtypes: float64(5), int64(2), str(3)
memory usage: 657.7 MB

In [10]:
fraud_df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
dtype: int64

In [11]:
fraud_df.duplicated().sum()

np.int64(0)

In [12]:
fraud_df[fraud_df.duplicated()]

Empty DataFrame
Columns: [step, type, amount, nameOrig, oldbalanceOrg, newbalanceOrig, nameDest, oldbalanceDest, newbalanceDest, isFraud]
Index: []

In [13]:
fraud_df.groupby("nameOrig")["isFraud"].sum().sort_values(ascending=False)

nameOrig
C1104869047    1
C1795788636    1
C1526831204    1
C1287154806    1
C165094398     1
              ..
C999990251     0
C999991140     0
C999991194     0
C999991491     0
C1000004053    0
Name: isFraud, Length: 6353307, dtype: int64

In [14]:
fraud_df.groupby("nameDest")["isFraud"].sum().sort_values(ascending=False)

nameDest
C1013511446    2
C1193568854    2
C1650668671    2
C185805228     2
C200064275     2
              ..
M999998692     0
M99999900      0
M999999089     0
M999999543     0
C1000022185    0
Name: isFraud, Length: 2722362, dtype: int64

In [15]:
fraud_df.drop(columns=["nameOrig","nameDest"],inplace=True)

In [16]:
fraud_df.columns

Index(['step', 'type', 'amount', 'oldbalanceOrg', 'newbalanceOrig',
       'oldbalanceDest', 'newbalanceDest', 'isFraud'],
      dtype='str')

In [17]:
fraud_df.head(10)

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
0,1,PAYMENT,9839.64,170136.00,160296.36,0.0,0.00,0
1,1,PAYMENT,1864.28,21249.00,19384.72,0.0,0.00,0
2,1,TRANSFER,181.00,181.00,0.00,0.0,0.00,1
3,1,CASH_OUT,181.00,181.00,0.00,21182.0,0.00,1
4,1,PAYMENT,11668.14,41554.00,29885.86,0.0,0.00,0
5,1,PAYMENT,7817.71,53860.00,46042.29,0.0,0.00,0
6,1,PAYMENT,7107.77,183195.00,176087.23,0.0,0.00,0
7,1,PAYMENT,7861.64,176087.23,168225.59,0.0,0.00,0
8,1,PAYMENT,4024.36,2671.00,0.00,0.0,0.00,0
9,1,DEBIT,5337.77,41720.00,36382.23,41898.0,40348.79,0

In [18]:
fraud_df["type"].value_counts()

type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [19]:
fraud_df["step"].value_counts()

step
19     51352
18     49579
187    49083
235    47491
307    46968
       ...
721        4
725        4
729        4
112        2
662        2
Name: count, Length: 743, dtype: int64

In [20]:
fraud_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 8 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            str
 2   amount          float64
 3   oldbalanceOrg   float64
 4   newbalanceOrig  float64
 5   oldbalanceDest  float64
 6   newbalanceDest  float64
 7   isFraud         int64
dtypes: float64(5), int64(2), str(1)
memory usage: 433.4 MB

In [59]:
fraud_df["orig_balance_diff"] = (
    fraud_df["oldbalanceOrg"]
    - fraud_df["newbalanceOrig"]
)

fraud_df["dest_balance_diff"] = (
    fraud_df["newbalanceDest"]
    - fraud_df["oldbalanceDest"]
)

In [60]:
fraud_df["orig_error"] = (
    fraud_df["oldbalanceOrg"]
    - fraud_df["amount"]
    - fraud_df["newbalanceOrig"]
)

fraud_df["dest_error"] = (
    fraud_df["oldbalanceDest"]
    + fraud_df["amount"]
    - fraud_df["newbalanceDest"]
)

In [61]:
fraud_df.head()

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,orig_balance_diff,dest_balance_diff,orig_error,dest_error
0,1,PAYMENT,9839.64,170136.0,160296.36,0.0,0.0,0,9839.64,0.0,0.0,9839.64
1,1,PAYMENT,1864.28,21249.0,19384.72,0.0,0.0,0,1864.28,0.0,0.0,1864.28
2,1,TRANSFER,181.00,181.0,0.00,0.0,0.0,1,181.00,0.0,0.0,181.00
3,1,CASH_OUT,181.00,181.0,0.00,21182.0,0.0,1,181.00,-21182.0,0.0,21363.00
4,1,PAYMENT,11668.14,41554.0,29885.86,0.0,0.0,0,11668.14,0.0,0.0,11668.14

In [62]:
X = fraud_df.drop("isFraud", axis=1)
y = fraud_df["isFraud"]

In [71]:
X.columns, y.name

(Index(['step', 'type', 'amount', 'oldbalanceOrg', 'newbalanceOrig',
        'oldbalanceDest', 'newbalanceDest', 'orig_balance_diff',
        'dest_balance_diff', 'orig_error', 'dest_error'],
       dtype='str'),
 'isFraud')

In [72]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column             Dtype
---  ------             -----
 0   step               int64
 1   type               str
 2   amount             float64
 3   oldbalanceOrg      float64
 4   newbalanceOrig     float64
 5   oldbalanceDest     float64
 6   newbalanceDest     float64
 7   orig_balance_diff  float64
 8   dest_balance_diff  float64
 9   orig_error         float64
 10  dest_error         float64
dtypes: float64(9), int64(1), str(1)
memory usage: 579.0 MB

In [73]:
num_cols = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

cat_cols = X.select_dtypes(
    include=["object", "string"]
).columns.tolist()

In [76]:
X = fraud_df.drop("isFraud", axis=1)
y = fraud_df["isFraud"]

In [77]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=10,
    stratify=y
)

In [78]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [79]:
num_pipeline = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)

cat_pipeline = Pipeline(
    steps=[
        ("onehot", OneHotEncoder())
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_pipeline, num_cols),
        ("cat", cat_pipeline, cat_cols)
    ]
)

In [81]:
from sklearn.model_selection import train_test_split

X_train_sample, _, y_train_sample, _ = train_test_split(
    X_train,
    y_train,
    train_size=500000,
    stratify=y_train,
    random_state=10
)

In [82]:
print(X_train_sample.shape)
print(y_train_sample.shape)

(500000, 11)
(500000,)

In [83]:
print(y_train.value_counts(normalize=True))
print(y_train_sample.value_counts(normalize=True))

isFraud
0    0.998709
1    0.001291
Name: proportion, dtype: float64
isFraud
0    0.99871
1    0.00129
Name: proportion, dtype: float64

In [84]:
lr_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "classifier",
            LogisticRegression(
                class_weight="balanced",
                random_state=10
            )
        )
    ]
)

In [85]:
lr_pipeline.fit(X_train_sample, y_train_sample)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest',
                                                   'orig_balance_diff',
                                                   'dest_balance_diff',
                                                   'orig_error',
                                                   'dest_error']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['type'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', random_state=10))])

In [86]:
dt_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "classifier",
            DecisionTreeClassifier(
                class_weight="balanced",
                random_state=10
            )
        )
    ]
)

In [87]:
dt_pipeline.fit(X_train_sample, y_train_sample)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest',
                                                   'orig_balance_diff',
                                                   'dest_balance_diff',
                                                   'orig_error',
                                                   'dest_error']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['type'])])),
                ('classifier',
                 DecisionTreeClassifier(class_weight='balanced',
                                        random_state=10))])

In [96]:
rf_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "classifier",
            RandomForestClassifier(
                n_estimators=100,
                class_weight="balanced",
                random_state=10,
                max_depth=15,
                n_jobs=-1
            )
        )
    ]
)

In [97]:
rf_pipeline.fit(X_train_sample, y_train_sample)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest',
                                                   'orig_balance_diff',
                                                   'dest_balance_diff',
                                                   'orig_error',
                                                   'dest_error']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['type'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced', max_depth=15,
                                        n_jobs=-1, random_state=10))])

In [98]:
y_pred_lr = lr_pipeline.predict(X_test)

In [99]:
y_pred_dt = dt_pipeline.predict(X_test)

In [100]:
y_pred_rf = rf_pipeline.predict(X_test)

In [101]:
print(confusion_matrix(y_pred_lr,y_test))

[[1824319      91]
 [  82003    2373]]

In [102]:
print(confusion_matrix(y_pred_dt,y_test))

[[1906309      14]
 [     13    2450]]

In [103]:
print(confusion_matrix(y_pred_rf,y_test))

[[1906320      38]
 [      2    2426]]

In [104]:
print(classification_report(y_pred_lr,y_test))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98   1824410
           1       0.96      0.03      0.05     84376

    accuracy                           0.96   1908786
   macro avg       0.96      0.51      0.52   1908786
weighted avg       0.96      0.96      0.94   1908786

In [105]:
print(classification_report(y_pred_dt,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906323
           1       0.99      0.99      0.99      2463

    accuracy                           1.00   1908786
   macro avg       1.00      1.00      1.00   1908786
weighted avg       1.00      1.00      1.00   1908786

In [106]:
print(classification_report(y_pred_rf,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906358
           1       0.98      1.00      0.99      2428

    accuracy                           1.00   1908786
   macro avg       0.99      1.00      1.00   1908786
weighted avg       1.00      1.00      1.00   1908786

NameError: name 'y_test' is not defined

In [ ]:
# num_cols= list(fraud_df.drop(columns=['type','isFraud']))
# cat_cols = list(fraud_df.select_dtypes(include='str').columns)

In [ ]:
# from sklearn.preprocessing import StandardScaler, OneHotEncoder
# from sklearn.pipeline import Pipeline
# from sklearn.compose import ColumnTransformer

In [ ]:
# num_pipeline = Pipeline(
#     steps=[
#         ("scaler", StandardScaler())
#     ]
# )

# cat_pipeline = Pipeline(
#     steps=[
#         ("onehot", OneHotEncoder())
#     ]
# )

# preprocessor = ColumnTransformer(
#     transformers=[
#         ("num", num_pipeline, num_cols),
#         ("cat", cat_pipeline, cat_cols)
#     ]
# )

In [ ]:
# fraud_df['isFraud'].value_counts()

isFraud
0    6354407
1       8213
Name: count, dtype: int64

In [ ]:
# from sklearn.model_selection import train_test_split

# X = fraud_df.drop("isFraud", axis=1)
# y = fraud_df["isFraud"]

# X_train, X_test, y_train, y_test = train_test_split(
#     X,
#     y,
#     test_size=0.3,
#     random_state=10,
#     stratify=y
# )

# # Shapes
# print("X_train shape:", X_train.shape)
# print("X_test shape :", X_test.shape)
# print("y_train shape:", y_train.shape)
# print("y_test shape :", y_test.shape)

# # Check class distribution
# print("\nOverall Distribution")
# print(y.value_counts(normalize=True) * 100)

# print("\nTrain Distribution")
# print(y_train.value_counts(normalize=True) * 100)

# print("\nTest Distribution")
# print(y_test.value_counts(normalize=True) * 100)

X_train shape: (4453834, 7)
X_test shape : (1908786, 7)
y_train shape: (4453834,)
y_test shape : (1908786,)

Overall Distribution
isFraud
0    99.870918
1     0.129082
Name: proportion, dtype: float64

Train Distribution
isFraud
0    99.87092
1     0.12908
Name: proportion, dtype: float64

Test Distribution
isFraud
0    99.870913
1     0.129087
Name: proportion, dtype: float64

In [ ]:
# lr_pipeline = Pipeline(
#     steps=[
#         ("preprocessor", preprocessor),
#         (
#             "classifier",
#             LogisticRegression(
#                 class_weight="balanced",
#                 random_state=10
#             )
#         )
#     ]
# )

In [ ]:
# lr_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['type'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', random_state=10))])

In [ ]:
# dt_pipeline = Pipeline(
#     steps=[
#         ("preprocessor", preprocessor),
#         (
#             "classifier",
#             DecisionTreeClassifier(
#                 class_weight="balanced",
#                 random_state=10
#             )
#         )
#     ]
# )

In [ ]:
# dt_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['type'])])),
                ('classifier',
                 DecisionTreeClassifier(class_weight='balanced',
                                        random_state=10))])

In [ ]:
# rf_pipeline = Pipeline(
#     steps=[
#         ("preprocessor", preprocessor),
#         (
#             "classifier",
#             RandomForestClassifier(
#                 n_estimators=100,
#                 class_weight="balanced",
#                 random_state=10,
#                 max_depth=12,
#                 n_jobs=-1
#             )
#         )
#     ]
# )

In [ ]:
# rf_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['type'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced', max_depth=12,
                                        n_jobs=-1, random_state=10))])

In [ ]:
# y_pred_lr = lr_pipeline.predict(X_test)
# y_prob_lr = lr_pipeline.predict_proba(X_test)[:, 1]

In [ ]:
# y_pred_dt = dt_pipeline.predict(X_test)
# y_prob_dt = dt_pipeline.predict_proba(X_test)[:, 1]

In [ ]:
# y_pred_rf = rf_pipeline.predict(X_test)
# y_prob_rf = rf_pipeline.predict_proba(X_test)[:, 1]

In [ ]:
# print(confusion_matrix(y_pred_lr,y_test))

[[1812840     128]
 [  93482    2336]]

In [ ]:
# print(confusion_matrix(y_pred_dt,y_test))

[[1906091     399]
 [    231    2065]]

In [ ]:
# print(confusion_matrix(y_pred_rf,y_test))

[[1887283      43]
 [  19039    2421]]

In [ ]:
# X.columns

Index(['step', 'type', 'amount', 'oldbalanceOrg', 'newbalanceOrig',
       'oldbalanceDest', 'newbalanceDest'],
      dtype='str')